-- EventReport — catalogue seed (rules, frameworks, controls, mapping).
-- GENERATED FILE: do not edit by hand.
-- Source: apps/web/lib/fixtures (rules, rule-controls, catalog, findings).
-- Regenerate with: node supabase/seed/generate.mjs

begin;

insert into public.finding_rules (code, severity, domain, title, description) values
  ('FW-001', 'critical', 'access', 'Administración expuesta en interfaz WAN', 'La administración por HTTPS o SSH responde en una interfaz conectada a internet. Cualquiera puede intentar autenticarse contra el equipo que protege la red.'),
  ('FW-002', 'high', 'access', 'Administrador sin segundo factor', 'Una cuenta administrativa entra solo con contraseña. Una contraseña filtrada basta para reconfigurar el firewall.'),
  ('FW-003', 'high', 'access', 'Administrador sin restricción de hosts de confianza', 'La cuenta puede autenticarse desde cualquier dirección. Limitarla a las IP de administración reduce la superficie de ataque sin costo.'),
  ('FW-004', 'medium', 'access', 'Más de dos administradores con perfil total', 'Varias cuentas con permisos completos diluyen la trazabilidad de los cambios y amplían el impacto de una credencial comprometida.'),
  ('FW-005', 'high', 'maintenance', 'Firmware fuera de soporte o con vulnerabilidad conocida', 'La versión instalada ya no recibe parches o tiene un CVE publicado con explotación conocida.'),
  ('FW-006', 'critical', 'policy', 'Política de origen y destino abiertos con todos los servicios', 'Una regla permite cualquier origen hacia cualquier destino en cualquier puerto. El firewall deja de filtrar en ese punto.'),
  ('FW-007', 'medium', 'policy', 'Políticas sin tráfico en 90 días', 'Reglas que nadie usa siguen abiertas. Cada una es una puerta que hay que revisar en la próxima auditoría.'),
  ('FW-008', 'medium', 'logging', 'Políticas permitidas sin registro', 'El tráfico que estas reglas permiten no queda en ningún log: no hay forma de reconstruir un incidente que pasó por ahí.'),
  ('FW-009', 'medium', 'policy', 'Políticas de salida sin inspección', 'Tráfico saliente sin IPS, antivirus, filtrado web ni control de aplicaciones. Las licencias están pagadas y sin usar.'),
  ('FW-010', 'high', 'policy', 'NAT entrante hacia administración o bases de datos', 'Hay un puerto publicado desde internet hacia un servicio de administración o una base de datos interna.'),
  ('FW-011', 'high', 'vpn', 'VPN de acceso remoto sin segundo factor', 'Los usuarios entran a la red interna con usuario y contraseña. Es el vector de ransomware más común en PYMES.'),
  ('FW-012', 'medium', 'crypto', 'VPN con cifrado obsoleto', 'TLS por debajo de 1.2, o IPsec con IKEv1, DES/3DES o grupos Diffie-Hellman de 1024 bits o menos.'),
  ('FW-013', 'medium', 'crypto', 'Certificado por vencer o autofirmado en portal público', 'El portal que ven los usuarios presenta un certificado que el navegador no valida, o que caduca pronto.'),
  ('FW-014', 'low', 'access', 'SNMP v1/v2c con comunidad por defecto', 'La comunidad de solo lectura sigue en el valor de fábrica y viaja sin cifrar. Expone el inventario de la red.'),
  ('FW-015', 'low', 'logging', 'Sin NTP o con desfase de reloj', 'El reloj del firewall se aparta más de 60 segundos. Los tiempos de los logs dejan de servir como evidencia.'),
  ('FW-016', 'medium', 'maintenance', 'Licencias de seguridad vencidas o por vencer', 'Las suscripciones de IPS, antivirus o filtrado web están vencidas o caducan pronto: las firmas dejan de actualizarse.'),
  ('FW-017', 'low', 'logging', 'Sin destino de syslog adicional al colector', 'Solo hay una copia de los registros. Los marcos que exigen retención larga piden un segundo destino.'),
  ('FW-018', 'medium', 'maintenance', 'Alta disponibilidad degradada', 'El clúster está configurado pero uno de los miembros no responde o no sincroniza. La redundancia no existe hoy.'),
  ('FW-019', 'medium', 'logging', 'Pérdida de eventos en el colector', 'Más del 1 % de las líneas de syslog se descartan. Los conteos del informe de actividad quedan por debajo de la realidad.'),
  ('FW-020', 'high', 'policy', 'Tráfico permitido hacia países de alto riesgo', 'Hay tráfico saliente autorizado hacia regiones sin relación con la operación del negocio y sin justificación registrada.'),
  ('OP-001', 'medium', 'policy', 'Sin revisión de reglas en los últimos seis meses', 'No se ha generado ni aprobado un informe de hardening en el período que exige el marco seleccionado.'),
  ('OP-002', 'medium', 'logging', 'Eventos críticos sin tratamiento en siete días', 'Hay alertas de alta severidad que nadie marcó como atendidas. Un evento sin cierre no es evidencia de control.'),
  ('OP-003', 'high', 'logging', 'Retención de registros inferior a la exigida', 'La retención combinada de bóveda local y agregados en la nube no alcanza lo que pide el marco activo.'),
  ('OP-004', 'low', 'logging', 'Cambios de configuración sin actor identificado', 'Hubo cambios cuya autoría no aparece en el syslog de administración: no se puede saber quién los hizo.')
on conflict (code) do update set severity = excluded.severity, domain = excluded.domain, title = excluded.title, description = excluded.description;

insert into public.frameworks (code, name, version, log_retention_days, total_controls, scope_note) values
  ('iso27001', 'ISO/IEC 27001:2022 Anexo A', '2022', 0, 93, 'EventReport aporta evidencia técnica del perímetro para tu SGSI. No sustituye la auditoría ni certifica el sistema de gestión.'),
  ('cis_v8', 'CIS Controls v8 (IG1/IG2)', '8.0', 0, 153, 'Estado por salvaguarda, más los ítems del CIS Benchmark de la marca cuando existe para tu equipo.'),
  ('pci_dss', 'PCI DSS v4.0.1', '4.0.1', 365, 250, 'Cubre los controles de seguridad de red. La retención de 12 meses del requisito 10.5.1 no se satisface con la bóveda local: hace falta un destino de registros adicional (FW-017).'),
  ('hipaa', 'HIPAA Security Rule (45 CFR 164)', '2013', 2190, 42, 'Evidencia de salvaguardas técnicas de red. HIPAA no es certificable; aplica si procesas datos de salud de entidades cubiertas en Estados Unidos.')
on conflict (code) do update set name = excluded.name, version = excluded.version, log_retention_days = excluded.log_retention_days, total_controls = excluded.total_controls, scope_note = excluded.scope_note;

insert into public.controls (framework_code, code, title, domain) values
  ('iso27001', '5.25', 'Evaluación y decisión sobre eventos de seguridad', 'Organizativos'),
  ('iso27001', '8.2', 'Derechos de acceso privilegiado', 'Tecnológicos'),
  ('iso27001', '8.5', 'Autenticación segura', 'Tecnológicos'),
  ('iso27001', '8.7', 'Protección contra software malicioso', 'Tecnológicos'),
  ('iso27001', '8.8', 'Gestión de vulnerabilidades técnicas', 'Tecnológicos'),
  ('iso27001', '8.9', 'Gestión de la configuración', 'Tecnológicos'),
  ('iso27001', '8.14', 'Redundancia de los recursos de tratamiento', 'Tecnológicos'),
  ('iso27001', '8.15', 'Registro de eventos', 'Tecnológicos'),
  ('iso27001', '8.16', 'Actividades de seguimiento', 'Tecnológicos'),
  ('iso27001', '8.17', 'Sincronización de relojes', 'Tecnológicos'),
  ('iso27001', '8.20', 'Seguridad de las redes', 'Tecnológicos'),
  ('iso27001', '8.24', 'Uso de criptografía', 'Tecnológicos'),
  ('iso27001', '8.32', 'Gestión de cambios', 'Tecnológicos'),
  ('cis_v8', '3.10', 'Cifrar los datos sensibles en tránsito', 'Protección de datos'),
  ('cis_v8', '4.2', 'Establecer y mantener configuración segura de red', 'Configuración segura'),
  ('cis_v8', '5.4', 'Restringir privilegios de administrador', 'Gestión de cuentas'),
  ('cis_v8', '6.4', 'Exigir MFA para el acceso remoto a la red', 'Control de acceso'),
  ('cis_v8', '6.5', 'Exigir MFA para el acceso administrativo', 'Control de acceso'),
  ('cis_v8', '7.4', 'Gestión automatizada de parches de aplicaciones', 'Vulnerabilidades'),
  ('cis_v8', '8.2', 'Recolectar registros de auditoría', 'Gestión de registros'),
  ('cis_v8', '8.4', 'Sincronizar los relojes de auditoría', 'Gestión de registros'),
  ('cis_v8', '8.5', 'Recolectar registros de auditoría detallados', 'Gestión de registros'),
  ('cis_v8', '8.9', 'Centralizar los registros de auditoría', 'Gestión de registros'),
  ('cis_v8', '8.10', 'Conservar los registros de auditoría', 'Gestión de registros'),
  ('cis_v8', '10.1', 'Desplegar y mantener software antimalware', 'Defensa antimalware'),
  ('cis_v8', '12.1', 'Mantener la infraestructura de red actualizada', 'Infraestructura de red'),
  ('cis_v8', '12.2', 'Establecer y mantener una arquitectura de red segura', 'Infraestructura de red'),
  ('cis_v8', '12.8', 'Establecer y mantener computación dedicada para tareas administrativas', 'Infraestructura de red'),
  ('cis_v8', '13.3', 'Desplegar una solución de detección de intrusiones', 'Monitoreo y defensa'),
  ('cis_v8', '13.10', 'Realizar filtrado a nivel de aplicación', 'Monitoreo y defensa'),
  ('cis_v8', '17.4', 'Establecer y mantener un proceso de respuesta a incidentes', 'Respuesta a incidentes'),
  ('pci_dss', '1.2.5', 'Puertos, protocolos y servicios permitidos identificados y aprobados', 'Requisito 1'),
  ('pci_dss', '1.2.7', 'Revisión periódica de las configuraciones de los NSC', 'Requisito 1'),
  ('pci_dss', '1.3.1', 'Tráfico entrante al entorno restringido a lo necesario', 'Requisito 1'),
  ('pci_dss', '1.3.2', 'Tráfico saliente del entorno restringido a lo necesario', 'Requisito 1'),
  ('pci_dss', '1.4.4', 'Los componentes que almacenan datos no son accesibles desde redes no confiables', 'Requisito 1'),
  ('pci_dss', '2.2.2', 'Cuentas y contraseñas por defecto eliminadas o cambiadas', 'Requisito 2'),
  ('pci_dss', '2.2.7', 'Todo acceso administrativo no consola está cifrado', 'Requisito 2'),
  ('pci_dss', '4.2.1', 'Criptografía fuerte durante la transmisión en redes públicas', 'Requisito 4'),
  ('pci_dss', '5.2.1', 'Solución antimalware desplegada y activa', 'Requisito 5'),
  ('pci_dss', '6.3.3', 'Componentes de software protegidos con los parches vigentes', 'Requisito 6'),
  ('pci_dss', '7.2.1', 'Modelo de control de acceso definido', 'Requisito 7'),
  ('pci_dss', '8.4.1', 'MFA para todo acceso administrativo no consola', 'Requisito 8'),
  ('pci_dss', '8.4.3', 'MFA para todo acceso remoto desde fuera de la red', 'Requisito 8'),
  ('pci_dss', '10.2.1', 'Registros de auditoría habilitados y activos', 'Requisito 10'),
  ('pci_dss', '10.2.1.6', 'Los registros identifican al usuario que originó el evento', 'Requisito 10'),
  ('pci_dss', '10.3.3', 'Los registros se respaldan en un servidor interno seguro', 'Requisito 10'),
  ('pci_dss', '10.4.1', 'Revisión de los registros de auditoría', 'Requisito 10'),
  ('pci_dss', '10.5.1', 'Doce meses de historial de registros, tres inmediatamente disponibles', 'Requisito 10'),
  ('pci_dss', '10.6.1', 'Relojes sincronizados en todos los sistemas', 'Requisito 10'),
  ('pci_dss', '11.5.1', 'Detección de intrusiones desplegada y monitoreada', 'Requisito 11'),
  ('hipaa', '164.308(a)(3)', 'Gestión de acceso de la fuerza laboral', 'Salvaguardas administrativas'),
  ('hipaa', '164.308(a)(5)(ii)(B)', 'Protección contra software malicioso', 'Salvaguardas administrativas'),
  ('hipaa', '164.308(a)(6)', 'Procedimientos de respuesta a incidentes', 'Salvaguardas administrativas'),
  ('hipaa', '164.308(a)(7)', 'Plan de contingencia', 'Salvaguardas administrativas'),
  ('hipaa', '164.308(a)(8)', 'Evaluación periódica de las salvaguardas', 'Salvaguardas administrativas'),
  ('hipaa', '164.312(a)(1)', 'Control de acceso', 'Salvaguardas técnicas'),
  ('hipaa', '164.312(b)', 'Controles de auditoría', 'Salvaguardas técnicas'),
  ('hipaa', '164.312(d)', 'Autenticación de la persona o entidad', 'Salvaguardas técnicas'),
  ('hipaa', '164.312(e)(1)', 'Seguridad de la transmisión', 'Salvaguardas técnicas'),
  ('hipaa', '164.316(b)(2)', 'Retención de la documentación por seis años', 'Requisitos de política')
on conflict (framework_code, code) do update set title = excluded.title, domain = excluded.domain;

insert into public.rule_controls (rule_code, framework_code, control_code) values
  ('FW-001', 'iso27001', '8.20'),
  ('FW-001', 'iso27001', '8.9'),
  ('FW-001', 'cis_v8', '4.2'),
  ('FW-001', 'cis_v8', '12.8'),
  ('FW-001', 'pci_dss', '1.3.1'),
  ('FW-001', 'pci_dss', '2.2.7'),
  ('FW-001', 'hipaa', '164.312(a)(1)'),
  ('FW-002', 'iso27001', '8.5'),
  ('FW-002', 'cis_v8', '6.5'),
  ('FW-002', 'pci_dss', '8.4.1'),
  ('FW-002', 'hipaa', '164.312(d)'),
  ('FW-003', 'iso27001', '8.5'),
  ('FW-003', 'iso27001', '8.20'),
  ('FW-003', 'cis_v8', '4.2'),
  ('FW-003', 'cis_v8', '12.8'),
  ('FW-003', 'pci_dss', '1.3.1'),
  ('FW-003', 'hipaa', '164.312(a)(1)'),
  ('FW-004', 'iso27001', '8.2'),
  ('FW-004', 'cis_v8', '5.4'),
  ('FW-004', 'pci_dss', '7.2.1'),
  ('FW-004', 'hipaa', '164.308(a)(3)'),
  ('FW-005', 'iso27001', '8.8'),
  ('FW-005', 'cis_v8', '7.4'),
  ('FW-005', 'cis_v8', '12.1'),
  ('FW-005', 'pci_dss', '6.3.3'),
  ('FW-005', 'hipaa', '164.308(a)(5)(ii)(B)'),
  ('FW-006', 'iso27001', '8.20'),
  ('FW-006', 'cis_v8', '4.2'),
  ('FW-006', 'cis_v8', '12.2'),
  ('FW-006', 'pci_dss', '1.2.5'),
  ('FW-006', 'pci_dss', '1.3.1'),
  ('FW-006', 'hipaa', '164.312(a)(1)'),
  ('FW-007', 'iso27001', '8.20'),
  ('FW-007', 'cis_v8', '4.2'),
  ('FW-007', 'pci_dss', '1.2.7'),
  ('FW-007', 'hipaa', '164.308(a)(8)'),
  ('FW-008', 'iso27001', '8.15'),
  ('FW-008', 'cis_v8', '8.2'),
  ('FW-008', 'cis_v8', '8.5'),
  ('FW-008', 'pci_dss', '10.2.1'),
  ('FW-008', 'hipaa', '164.312(b)'),
  ('FW-009', 'iso27001', '8.7'),
  ('FW-009', 'iso27001', '8.20'),
  ('FW-009', 'cis_v8', '13.3'),
  ('FW-009', 'cis_v8', '13.10'),
  ('FW-009', 'pci_dss', '5.2.1'),
  ('FW-009', 'pci_dss', '11.5.1'),
  ('FW-009', 'hipaa', '164.308(a)(5)(ii)(B)'),
  ('FW-010', 'iso27001', '8.20'),
  ('FW-010', 'cis_v8', '12.2'),
  ('FW-010', 'pci_dss', '1.3.1'),
  ('FW-010', 'pci_dss', '1.4.4'),
  ('FW-010', 'hipaa', '164.312(a)(1)'),
  ('FW-011', 'iso27001', '8.5'),
  ('FW-011', 'cis_v8', '6.4'),
  ('FW-011', 'pci_dss', '8.4.3'),
  ('FW-011', 'hipaa', '164.312(d)'),
  ('FW-012', 'iso27001', '8.24'),
  ('FW-012', 'cis_v8', '3.10'),
  ('FW-012', 'pci_dss', '4.2.1'),
  ('FW-012', 'hipaa', '164.312(e)(1)'),
  ('FW-013', 'iso27001', '8.24'),
  ('FW-013', 'cis_v8', '3.10'),
  ('FW-013', 'pci_dss', '4.2.1'),
  ('FW-013', 'hipaa', '164.312(e)(1)'),
  ('FW-014', 'iso27001', '8.20'),
  ('FW-014', 'cis_v8', '4.2'),
  ('FW-014', 'pci_dss', '2.2.2'),
  ('FW-014', 'hipaa', '164.312(a)(1)'),
  ('FW-015', 'iso27001', '8.17'),
  ('FW-015', 'cis_v8', '8.4'),
  ('FW-015', 'pci_dss', '10.6.1'),
  ('FW-015', 'hipaa', '164.312(b)'),
  ('FW-016', 'iso27001', '8.7'),
  ('FW-016', 'iso27001', '8.8'),
  ('FW-016', 'cis_v8', '10.1'),
  ('FW-016', 'cis_v8', '13.3'),
  ('FW-016', 'pci_dss', '5.2.1'),
  ('FW-016', 'pci_dss', '11.5.1'),
  ('FW-016', 'hipaa', '164.308(a)(5)(ii)(B)'),
  ('FW-017', 'iso27001', '8.15'),
  ('FW-017', 'cis_v8', '8.9'),
  ('FW-017', 'cis_v8', '8.10'),
  ('FW-017', 'pci_dss', '10.3.3'),
  ('FW-017', 'pci_dss', '10.5.1'),
  ('FW-017', 'hipaa', '164.316(b)(2)'),
  ('FW-018', 'iso27001', '8.14'),
  ('FW-018', 'hipaa', '164.308(a)(7)'),
  ('FW-019', 'iso27001', '8.15'),
  ('FW-019', 'cis_v8', '8.2'),
  ('FW-019', 'pci_dss', '10.2.1'),
  ('FW-019', 'pci_dss', '10.3.3'),
  ('FW-019', 'hipaa', '164.312(b)'),
  ('FW-020', 'iso27001', '8.20'),
  ('FW-020', 'cis_v8', '12.2'),
  ('FW-020', 'pci_dss', '1.3.2'),
  ('FW-020', 'hipaa', '164.312(a)(1)'),
  ('OP-001', 'iso27001', '8.20'),
  ('OP-001', 'cis_v8', '4.2'),
  ('OP-001', 'pci_dss', '1.2.7'),
  ('OP-001', 'hipaa', '164.308(a)(8)'),
  ('OP-002', 'iso27001', '5.25'),
  ('OP-002', 'iso27001', '8.16'),
  ('OP-002', 'cis_v8', '17.4'),
  ('OP-002', 'pci_dss', '10.4.1'),
  ('OP-002', 'hipaa', '164.308(a)(6)'),
  ('OP-003', 'iso27001', '8.15'),
  ('OP-003', 'cis_v8', '8.10'),
  ('OP-003', 'pci_dss', '10.5.1'),
  ('OP-003', 'hipaa', '164.316(b)(2)'),
  ('OP-004', 'iso27001', '8.15'),
  ('OP-004', 'iso27001', '8.32'),
  ('OP-004', 'cis_v8', '8.5'),
  ('OP-004', 'pci_dss', '10.2.1.6'),
  ('OP-004', 'hipaa', '164.312(b)')
on conflict do nothing;

insert into public.rule_remediations (rule_code, brand, steps) values
  ('FW-001', 'fortigate', array['Entra a Network › Interfaces y abre la interfaz WAN señalada en el hallazgo.','En Administrative Access desmarca HTTPS, SSH y PING.','Si necesitas administrar desde fuera, deja solo HTTPS y agrega las IP de administración en System › Admin › Trusted Hosts.','Confirma por CLI: config system interface, edit <interfaz>, unset allowaccess.']),
  ('FW-011', 'fortigate', array['Crea el servidor de segundo factor en User & Authentication › FortiToken o RADIUS.','Asigna el token a cada usuario del grupo de VPN.','En VPN › SSL-VPN Settings exige el grupo con MFA en Authentication/Portal Mapping.','Prueba con una cuenta antes de cerrar el acceso al resto.']),
  ('FW-006', 'fortigate', array['Abre Policy & Objects › Firewall Policy y localiza la política señalada en el hallazgo.','Reemplaza el origen y el destino any por los grupos de direcciones reales.','Cambia el servicio ALL por los puertos que la aplicación necesita.','Deja la política deshabilitada un día y revisa el contador de aciertos antes de borrarla.']),
  ('FW-009', 'sophos_xg', array['Entra a Rules and policies › Firewall rules y abre la regla señalada en el hallazgo.','En Security features activa IPS, protección web y control de aplicaciones.','Selecciona los perfiles predeterminados de tu política de salida.','Verifica el consumo de CPU la primera hora: la inspección agrega carga.']),
  ('FW-014', 'sophos_xg', array['Ve a Administration › SNMP y elimina la comunidad public.','Crea un usuario SNMPv3 con autenticación SHA y cifrado AES.','Restringe el acceso a la IP del sistema de monitoreo.'])
on conflict (rule_code, brand) do update set steps = excluded.steps;

commit;
