-- EventReport — catalogue seed (rules, frameworks, controls, mapping).
-- GENERATED FILE: do not edit by hand.
-- Source: apps/web/lib/fixtures (rules, rule-controls, catalog, findings).
-- Regenerate with: node supabase/seed/generate.mjs

begin;

insert into public.finding_rules (code, severity, domain, title, description) values
  ('FW-001', 'critical', 'access', 'Administración expuesta en interfaz WAN', 'La administración por HTTPS o SSH responde en una interfaz conectada a internet. Cualquiera puede intentar autenticarse contra el equipo que protege la red.'),
  ('FW-002', 'high', 'access', 'Administrador sin segundo factor', 'Una cuenta administrativa entra solo con contraseña. Una contraseña filtrada basta para reconfigurar el firewall.'),
  ('FW-003', 'high', 'access', 'Administrador sin restricción de hosts de confianza', 'La cuenta puede autenticarse desde cualquier dirección. Limitarla a las IP de administración reduce la superficie de ataque sin costo.'),
  ('FW-004', 'medium', 'access', 'Más de dos administradores con perfil total', 'Varias cuentas con permisos completos diluyen la trazabilidad de los cambios y amplían el impacto de una credencial comprometida.'),
  ('FW-005', 'high', 'maintenance', 'Firmware fuera de soporte o con vulnerabilidad conocida', 'La versión instalada ya no recibe parches o tiene un CVE publicado con explotación conocida.'),
  ('FW-006', 'critical', 'policy', 'Política de origen y destino abiertos con todos los servicios', 'Una regla permite cualquier origen hacia cualquier destino en cualquier puerto. El firewall deja de filtrar en ese punto.'),
  ('FW-007', 'medium', 'policy', 'Políticas sin tráfico en 90 días', 'Reglas que nadie usa siguen abiertas. Cada una es una puerta que hay que revisar en la próxima auditoría.'),
  ('FW-008', 'medium', 'logging', 'Políticas permitidas sin registro', 'El tráfico que estas reglas permiten no queda en ningún log: no hay forma de reconstruir un incidente que pasó por ahí.'),
  ('FW-009', 'medium', 'policy', 'Políticas de salida sin inspección', 'Tráfico saliente sin IPS, antivirus, filtrado web ni control de aplicaciones. Las licencias están pagadas y sin usar.'),
  ('FW-010', 'high', 'policy', 'NAT entrante hacia administración o bases de datos', 'Hay un puerto publicado desde internet hacia un servicio de administración o una base de datos interna.'),
  ('FW-011', 'high', 'vpn', 'VPN de acceso remoto sin segundo factor', 'Los usuarios entran a la red interna con usuario y contraseña. Es el vector de ransomware más común en PYMES.'),
  ('FW-012', 'medium', 'crypto', 'VPN con cifrado obsoleto', 'TLS por debajo de 1.2, o IPsec con IKEv1, DES/3DES o grupos Diffie-Hellman de 1024 bits o menos.'),
  ('FW-013', 'medium', 'crypto', 'Certificado por vencer o autofirmado en portal público', 'El portal que ven los usuarios presenta un certificado que el navegador no valida, o que caduca pronto.'),
  ('FW-014', 'low', 'access', 'SNMP v1/v2c con comunidad por defecto', 'La comunidad de solo lectura sigue en el valor de fábrica y viaja sin cifrar. Expone el inventario de la red.'),
  ('FW-015', 'low', 'logging', 'Sin NTP o con desfase de reloj', 'El reloj del firewall se aparta más de 60 segundos. Los tiempos de los logs dejan de servir como evidencia.'),
  ('FW-016', 'medium', 'maintenance', 'Licencias de seguridad vencidas o por vencer', 'Las suscripciones de IPS, antivirus o filtrado web están vencidas o caducan pronto: las firmas dejan de actualizarse.'),
  ('FW-017', 'low', 'logging', 'Sin destino de syslog adicional al colector', 'Solo hay una copia de los registros. Los marcos que exigen retención larga piden un segundo destino.'),
  ('FW-018', 'medium', 'maintenance', 'Alta disponibilidad degradada', 'El clúster está configurado pero uno de los miembros no responde o no sincroniza. La redundancia no existe hoy.'),
  ('FW-019', 'medium', 'logging', 'Pérdida de eventos en el colector', 'Más del 1 % de las líneas de syslog se descartan. Los conteos del informe de actividad quedan por debajo de la realidad.'),
  ('FW-020', 'high', 'policy', 'Tráfico permitido hacia países de alto riesgo', 'Hay tráfico saliente autorizado hacia regiones sin relación con la operación del negocio y sin justificación registrada.'),
  ('OP-001', 'medium', 'policy', 'Sin revisión de reglas en los últimos seis meses', 'No se ha generado ni aprobado un informe de hardening en el período que exige el marco seleccionado.'),
  ('OP-002', 'medium', 'logging', 'Eventos críticos sin tratamiento en siete días', 'Hay alertas de alta severidad que nadie marcó como atendidas. Un evento sin cierre no es evidencia de control.'),
  ('OP-003', 'high', 'logging', 'Retención de registros inferior a la exigida', 'La retención combinada de bóveda local y agregados en la nube no alcanza lo que pide el marco activo.'),
  ('OP-004', 'low', 'logging', 'Cambios de configuración sin actor identificado', 'Hubo cambios cuya autoría no aparece en el syslog de administración: no se puede saber quién los hizo.')
on conflict (code) do update set severity = excluded.severity, domain = excluded.domain, title = excluded.title, description = excluded.description;

insert into public.frameworks (code, name, version, log_retention_days, total_controls, scope_note) values
  ('iso27001', 'ISO/IEC 27001:2022 Anexo A', '2022', 0, 93, 'EventReport aporta evidencia técnica del perímetro para tu SGSI. No sustituye la auditoría ni certifica el sistema de gestión.'),
  ('cis_v8', 'CIS Controls v8 (IG1/IG2)', '8.0', 0, 153, 'Estado por salvaguarda, más los ítems del CIS Benchmark de la marca cuando existe para tu equipo.'),
  ('pci_dss', 'PCI DSS v4.0.1', '4.0.1', 365, 250, 'Cubre los controles de seguridad de red. La retención de 12 meses del requisito 10.5.1 no se satisface con la bóveda local: hace falta un destino de registros adicional (FW-017).'),
  ('hipaa', 'HIPAA Security Rule (45 CFR 164)', '2013', 2190, 42, 'Evidencia de salvaguardas técnicas de red. HIPAA no es certificable; aplica si procesas datos de salud de entidades cubiertas en Estados Unidos.')
on conflict (code) do update set name = excluded.name, version = excluded.version, log_retention_days = excluded.log_retention_days, total_controls = excluded.total_controls, scope_note = excluded.scope_note;

insert into public.controls (framework_code, code, title, domain) values
  ('iso27001', '5.25', 'Evaluación y decisión sobre eventos de seguridad', 'Organizativos'),
  ('iso27001', '8.2', 'Derechos de acceso privilegiado', 'Tecnológicos'),
  ('iso27001', '8.5', 'Autenticación segura', 'Tecnológicos'),
  ('iso27001', '8.7', 'Protección contra software malicioso', 'Tecnológicos'),
  ('iso27001', '8.8', 'Gestión de vulnerabilidades técnicas', 'Tecnológicos'),
  ('iso27001', '8.9', 'Gestión de la configuración', 'Tecnológicos'),
  ('iso27001', '8.14', 'Redundancia de los recursos de tratamiento', 'Tecnológicos'),
  ('iso27001', '8.15', 'Registro de eventos', 'Tecnológicos'),
  ('iso27001', '8.16', 'Actividades de seguimiento', 'Tecnológicos'),
  ('iso27001', '8.17', 'Sincronización de relojes', 'Tecnológicos'),
  ('iso27001', '8.20', 'Seguridad de las redes', 'Tecnológicos'),
  ('iso27001', '8.24', 'Uso de criptografía', 'Tecnológicos'),
  ('iso27001', '8.32', 'Gestión de cambios', 'Tecnológicos'),
  ('cis_v8', '3.10', 'Cifrar los datos sensibles en tránsito', 'Protección de datos'),
  ('cis_v8', '4.2', 'Establecer y mantener configuración segura de red', 'Configuración segura'),
  ('cis_v8', '5.4', 'Restringir privilegios de administrador', 'Gestión de cuentas'),
  ('cis_v8', '6.4', 'Exigir MFA para el acceso remoto a la red', 'Control de acceso'),
  ('cis_v8', '6.5', 'Exigir MFA para el acceso administrativo', 'Control de acceso'),
  ('cis_v8', '7.4', 'Gestión automatizada de parches de aplicaciones', 'Vulnerabilidades'),
  ('cis_v8', '8.2', 'Recolectar registros de auditoría', 'Gestión de registros'),
  ('cis_v8', '8.4', 'Sincronizar los relojes de auditoría', 'Gestión de registros'),
  ('cis_v8', '8.5', 'Recolectar registros de auditoría detallados', 'Gestión de registros'),
  ('cis_v8', '8.9', 'Centralizar los registros de auditoría', 'Gestión de registros'),
  ('cis_v8', '8.10', 'Conservar los registros de auditoría', 'Gestión de registros'),
  ('cis_v8', '10.1', 'Desplegar y mantener software antimalware', 'Defensa antimalware'),
  ('cis_v8', '12.1', 'Mantener la infraestructura de red actualizada', 'Infraestructura de red'),
  ('cis_v8', '12.2', 'Establecer y mantener una arquitectura de red segura', 'Infraestructura de red'),
  ('cis_v8', '12.8', 'Establecer y mantener computación dedicada para tareas administrativas', 'Infraestructura de red'),
  ('cis_v8', '13.3', 'Desplegar una solución de detección de intrusiones', 'Monitoreo y defensa'),
  ('cis_v8', '13.10', 'Realizar filtrado a nivel de aplicación', 'Monitoreo y defensa'),
  ('cis_v8', '17.4', 'Establecer y mantener un proceso de respuesta a incidentes', 'Respuesta a incidentes'),
  ('pci_dss', '1.2.5', 'Puertos, protocolos y servicios permitidos identificados y aprobados', 'Requisito 1'),
  ('pci_dss', '1.2.7', 'Revisión periódica de las configuraciones de los NSC', 'Requisito 1'),
  ('pci_dss', '1.3.1', 'Tráfico entrante al entorno restringido a lo necesario', 'Requisito 1'),
  ('pci_dss', '1.3.2', 'Tráfico saliente del entorno restringido a lo necesario', 'Requisito 1'),
  ('pci_dss', '1.4.4', 'Los componentes que almacenan datos no son accesibles desde redes no confiables', 'Requisito 1'),
  ('pci_dss', '2.2.2', 'Cuentas y contraseñas por defecto eliminadas o cambiadas', 'Requisito 2'),
  ('pci_dss', '2.2.7', 'Todo acceso administrativo no consola está cifrado', 'Requisito 2'),
  ('pci_dss', '4.2.1', 'Criptografía fuerte durante la transmisión en redes públicas', 'Requisito 4'),
  ('pci_dss', '5.2.1', 'Solución antimalware desplegada y activa', 'Requisito 5'),
  ('pci_dss', '6.3.3', 'Componentes de software protegidos con los parches vigentes', 'Requisito 6'),
  ('pci_dss', '7.2.1', 'Modelo de control de acceso definido', 'Requisito 7'),
  ('pci_dss', '8.4.1', 'MFA para todo acceso administrativo no consola', 'Requisito 8'),
  ('pci_dss', '8.4.3', 'MFA para todo acceso remoto desde fuera de la red', 'Requisito 8'),
  ('pci_dss', '10.2.1', 'Registros de auditoría habilitados y activos', 'Requisito 10'),
  ('pci_dss', '10.2.1.6', 'Los registros identifican al usuario que originó el evento', 'Requisito 10'),
  ('pci_dss', '10.3.3', 'Los registros se respaldan en un servidor interno seguro', 'Requisito 10'),
  ('pci_dss', '10.4.1', 'Revisión de los registros de auditoría', 'Requisito 10'),
  ('pci_dss', '10.5.1', 'Doce meses de historial de registros, tres inmediatamente disponibles', 'Requisito 10'),
  ('pci_dss', '10.6.1', 'Relojes sincronizados en todos los sistemas', 'Requisito 10'),
  ('pci_dss', '11.5.1', 'Detección de intrusiones desplegada y monitoreada', 'Requisito 11'),
  ('hipaa', '164.308(a)(3)', 'Gestión de acceso de la fuerza laboral', 'Salvaguardas administrativas'),
  ('hipaa', '164.308(a)(5)(ii)(B)', 'Protección contra software malicioso', 'Salvaguardas administrativas'),
  ('hipaa', '164.308(a)(6)', 'Procedimientos de respuesta a incidentes', 'Salvaguardas administrativas'),
  ('hipaa', '164.308(a)(7)', 'Plan de contingencia', 'Salvaguardas administrativas'),
  ('hipaa', '164.308(a)(8)', 'Evaluación periódica de las salvaguardas', 'Salvaguardas administrativas'),
  ('hipaa', '164.312(a)(1)', 'Control de acceso', 'Salvaguardas técnicas'),
  ('hipaa', '164.312(b)', 'Controles de auditoría', 'Salvaguardas técnicas'),
  ('hipaa', '164.312(d)', 'Autenticación de la persona o entidad', 'Salvaguardas técnicas'),
  ('hipaa', '164.312(e)(1)', 'Seguridad de la transmisión', 'Salvaguardas técnicas'),
  ('hipaa', '164.316(b)(2)', 'Retención de la documentación por seis años', 'Requisitos de política')
on conflict (framework_code, code) do update set title = excluded.title, domain = excluded.domain;

insert into public.rule_controls (rule_code, framework_code, control_code) values
  ('FW-001', 'iso27001', '8.20'),
  ('FW-001', 'iso27001', '8.9'),
  ('FW-001', 'cis_v8', '4.2'),
  ('FW-001', 'cis_v8', '12.8'),
  ('FW-001', 'pci_dss', '1.3.1'),
  ('FW-001', 'pci_dss', '2.2.7'),
  ('FW-001', 'hipaa', '164.312(a)(1)'),
  ('FW-002', 'iso27001', '8.5'),
  ('FW-002', 'cis_v8', '6.5'),
  ('FW-002', 'pci_dss', '8.4.1'),
  ('FW-002', 'hipaa', '164.312(d)'),
  ('FW-003', 'iso27001', '8.5'),
  ('FW-003', 'iso27001', '8.20'),
  ('FW-003', 'cis_v8', '4.2'),
  ('FW-003', 'cis_v8', '12.8'),
  ('FW-003', 'pci_dss', '1.3.1'),
  ('FW-003', 'hipaa', '164.312(a)(1)'),
  ('FW-004', 'iso27001', '8.2'),
  ('FW-004', 'cis_v8', '5.4'),
  ('FW-004', 'pci_dss', '7.2.1'),
  ('FW-004', 'hipaa', '164.308(a)(3)'),
  ('FW-005', 'iso27001', '8.8'),
  ('FW-005', 'cis_v8', '7.4'),
  ('FW-005', 'cis_v8', '12.1'),
  ('FW-005', 'pci_dss', '6.3.3'),
  ('FW-005', 'hipaa', '164.308(a)(5)(ii)(B)'),
  ('FW-006', 'iso27001', '8.20'),
  ('FW-006', 'cis_v8', '4.2'),
  ('FW-006', 'cis_v8', '12.2'),
  ('FW-006', 'pci_dss', '1.2.5'),
  ('FW-006', 'pci_dss', '1.3.1'),
  ('FW-006', 'hipaa', '164.312(a)(1)'),
  ('FW-007', 'iso27001', '8.20'),
  ('FW-007', 'cis_v8', '4.2'),
  ('FW-007', 'pci_dss', '1.2.7'),
  ('FW-007', 'hipaa', '164.308(a)(8)'),
  ('FW-008', 'iso27001', '8.15'),
  ('FW-008', 'cis_v8', '8.2'),
  ('FW-008', 'cis_v8', '8.5'),
  ('FW-008', 'pci_dss', '10.2.1'),
  ('FW-008', 'hipaa', '164.312(b)'),
  ('FW-009', 'iso27001', '8.7'),
  ('FW-009', 'iso27001', '8.20'),
  ('FW-009', 'cis_v8', '13.3'),
  ('FW-009', 'cis_v8', '13.10'),
  ('FW-009', 'pci_dss', '5.2.1'),
  ('FW-009', 'pci_dss', '11.5.1'),
  ('FW-009', 'hipaa', '164.308(a)(5)(ii)(B)'),
  ('FW-010', 'iso27001', '8.20'),
  ('FW-010', 'cis_v8', '12.2'),
  ('FW-010', 'pci_dss', '1.3.1'),
  ('FW-010', 'pci_dss', '1.4.4'),
  ('FW-010', 'hipaa', '164.312(a)(1)'),
  ('FW-011', 'iso27001', '8.5'),
  ('FW-011', 'cis_v8', '6.4'),
  ('FW-011', 'pci_dss', '8.4.3'),
  ('FW-011', 'hipaa', '164.312(d)'),
  ('FW-012', 'iso27001', '8.24'),
  ('FW-012', 'cis_v8', '3.10'),
  ('FW-012', 'pci_dss', '4.2.1'),
  ('FW-012', 'hipaa', '164.312(e)(1)'),
  ('FW-013', 'iso27001', '8.24'),
  ('FW-013', 'cis_v8', '3.10'),
  ('FW-013', 'pci_dss', '4.2.1'),
  ('FW-013', 'hipaa', '164.312(e)(1)'),
  ('FW-014', 'iso27001', '8.20'),
  ('FW-014', 'cis_v8', '4.2'),
  ('FW-014', 'pci_dss', '2.2.2'),
  ('FW-014', 'hipaa', '164.312(a)(1)'),
  ('FW-015', 'iso27001', '8.17'),
  ('FW-015', 'cis_v8', '8.4'),
  ('FW-015', 'pci_dss', '10.6.1'),
  ('FW-015', 'hipaa', '164.312(b)'),
  ('FW-016', 'iso27001', '8.7'),
  ('FW-016', 'iso27001', '8.8'),
  ('FW-016', 'cis_v8', '10.1'),
  ('FW-016', 'cis_v8', '13.3'),
  ('FW-016', 'pci_dss', '5.2.1'),
  ('FW-016', 'pci_dss', '11.5.1'),
  ('FW-016', 'hipaa', '164.308(a)(5)(ii)(B)'),
  ('FW-017', 'iso27001', '8.15'),
  ('FW-017', 'cis_v8', '8.9'),
  ('FW-017', 'cis_v8', '8.10'),
  ('FW-017', 'pci_dss', '10.3.3'),
  ('FW-017', 'pci_dss', '10.5.1'),
  ('FW-017', 'hipaa', '164.316(b)(2)'),
  ('FW-018', 'iso27001', '8.14'),
  ('FW-018', 'hipaa', '164.308(a)(7)'),
  ('FW-019', 'iso27001', '8.15'),
  ('FW-019', 'cis_v8', '8.2'),
  ('FW-019', 'pci_dss', '10.2.1'),
  ('FW-019', 'pci_dss', '10.3.3'),
  ('FW-019', 'hipaa', '164.312(b)'),
  ('FW-020', 'iso27001', '8.20'),
  ('FW-020', 'cis_v8', '12.2'),
  ('FW-020', 'pci_dss', '1.3.2'),
  ('FW-020', 'hipaa', '164.312(a)(1)'),
  ('OP-001', 'iso27001', '8.20'),
  ('OP-001', 'cis_v8', '4.2'),
  ('OP-001', 'pci_dss', '1.2.7'),
  ('OP-001', 'hipaa', '164.308(a)(8)'),
  ('OP-002', 'iso27001', '5.25'),
  ('OP-002', 'iso27001', '8.16'),
  ('OP-002', 'cis_v8', '17.4'),
  ('OP-002', 'pci_dss', '10.4.1'),
  ('OP-002', 'hipaa', '164.308(a)(6)'),
  ('OP-003', 'iso27001', '8.15'),
  ('OP-003', 'cis_v8', '8.10'),
  ('OP-003', 'pci_dss', '10.5.1'),
  ('OP-003', 'hipaa', '164.316(b)(2)'),
  ('OP-004', 'iso27001', '8.15'),
  ('OP-004', 'iso27001', '8.32'),
  ('OP-004', 'cis_v8', '8.5'),
  ('OP-004', 'pci_dss', '10.2.1.6'),
  ('OP-004', 'hipaa', '164.312(b)')
on conflict do nothing;

insert into public.rule_remediations (rule_code, brand, steps) values
  ('FW-001', 'fortigate', array['Entra a Network › Interfaces y abre la interfaz WAN señalada en el hallazgo.','En Administrative Access desmarca HTTPS, SSH y PING.','Si necesitas administrar desde fuera, deja solo HTTPS y agrega las IP de administración en System › Admin › Trusted Hosts.','Confirma por CLI: config system interface, edit <interfaz>, unset allowaccess.']),
  ('FW-011', 'fortigate', array['Crea el servidor de segundo factor en User & Authentication › FortiToken o RADIUS.','Asigna el token a cada usuario del grupo de VPN.','En VPN › SSL-VPN Settings exige el grupo con MFA en Authentication/Portal Mapping.','Prueba con una cuenta antes de cerrar el acceso al resto.']),
  ('FW-006', 'fortigate', array['Abre Policy & Objects › Firewall Policy y localiza la política señalada en el hallazgo.','Reemplaza el origen y el destino any por los grupos de direcciones reales.','Cambia el servicio ALL por los puertos que la aplicación necesita.','Deja la política deshabilitada un día y revisa el contador de aciertos antes de borrarla.']),
  ('FW-009', 'sophos_xg', array['Entra a Rules and policies › Firewall rules y abre la regla señalada en el hallazgo.','En Security features activa IPS, protección web y control de aplicaciones.','Selecciona los perfiles predeterminados de tu política de salida.','Verifica el consumo de CPU la primera hora: la inspección agrega carga.']),
  ('FW-014', 'sophos_xg', array['Ve a Administration › SNMP y elimina la comunidad public.','Crea un usuario SNMPv3 con autenticación SHA y cifrado AES.','Restringe el acceso a la IP del sistema de monitoreo.']),
  ('FW-002', 'fortigate', array['Entra a System > Administrators y abre cada cuenta con perfil super_admin.','Activa Two-factor Authentication y asigna un FortiToken (móvil o físico) o un servidor RADIUS con MFA.','Registra el token con el administrador presente y pídele que inicie sesión antes de cerrar la ventana.','Verifica por CLI: config system admin, show, y confirma que two-factor no quede en disable.']),
  ('FW-003', 'fortigate', array['Entra a System > Administrators y abre la cuenta señalada en el hallazgo.','Activa Restrict login to trusted hosts y agrega las redes desde donde se administra, con máscara exacta.','Deja siempre al menos un rango válido: si los tres quedan en 0.0.0.0/0 la restricción no existe.','Prueba desde una IP fuera del rango: la sesión debe rechazarse antes de pedir contraseña.']),
  ('FW-004', 'fortigate', array['Revisa System > Administrators y decide quién necesita de verdad perfil super_admin.','Crea perfiles acotados en System > Admin Profiles, por ejemplo solo lectura o solo políticas.','Reasigna a los administradores sobrantes al perfil acotado; no borres cuentas, cámbiales el perfil.','Deja constancia de quién aprobó cada perfil total: es la evidencia que pide la auditoría.']),
  ('FW-005', 'fortigate', array['Consulta la versión instalada en Dashboard > Status y compárala con el ciclo de vida publicado por Fortinet.','Descarga la versión estable recomendada para tu modelo desde el portal de soporte de Fortinet.','Respalda la configuración en System > Configuration > Backup y programa ventana de mantenimiento.','Sigue la ruta de actualización oficial: saltar versiones puede corromper la configuración.']),
  ('FW-007', 'fortigate', array['Abre Policy & Objects > Firewall Policy y activa la columna Hit Count con rango de 90 días.','Deshabilita, sin borrar, las políticas sin aciertos y anota la fecha.','Espera al menos dos semanas por si aparece un proceso mensual que las necesitaba.','Borra las que sigan sin uso y guarda el respaldo previo por si hay que revertir.']),
  ('FW-008', 'fortigate', array['Abre Policy & Objects > Firewall Policy y filtra las políticas con acción accept.','En cada una activa Log Allowed Traffic en All Sessions.','Si el equipo sufre por volumen, deja Security Events solo en políticas internas de bajo riesgo, nunca en las de salida a internet.','Confirma en Log & Report que los eventos llegan al colector después del cambio.']),
  ('FW-009', 'fortigate', array['Abre Policy & Objects > Firewall Policy y localiza las políticas de salida a internet.','En Security Profiles activa AntiVirus, Web Filter, Application Control e IPS con los perfiles de tu política.','Activa inspección SSL: certificate-inspection como mínimo, deep-inspection si ya distribuiste el certificado.','Revisa CPU y memoria la primera hora: la inspección agrega carga real al equipo.']),
  ('FW-010', 'fortigate', array['Abre Policy & Objects > Virtual IPs y revisa cada VIP publicada hacia internet.','Elimina las que publiquen RDP 3389, SSH 22, SMB 445 o puertos de base de datos.','Si el acceso es necesario, sustitúyelo por VPN con segundo factor en lugar de publicar el puerto.','Para lo que deba seguir publicado, limita Source Address a las IP de origen conocidas.']),
  ('FW-012', 'fortigate', array['Abre VPN > IPsec Tunnels y edita la fase 1 y la fase 2 del túnel señalado.','Retira DES, 3DES, MD5 y SHA1; deja AES-256 con SHA-256 o superior y DH group 14 o mayor.','Coordina el cambio con el extremo remoto: el túnel cae hasta que ambos lados coincidan.','Para SSL-VPN, en VPN > SSL-VPN Settings fija Algorithm en High y deshabilita TLS 1.0 y 1.1.']),
  ('FW-013', 'fortigate', array['Revisa System > Certificates y localiza el certificado del portal señalado.','Emite o renueva un certificado de una autoridad pública para el nombre que usan los usuarios.','Impórtalo y asígnalo en VPN > SSL-VPN Settings o en la VIP correspondiente.','Programa el recordatorio de renovación: un certificado vencido deja a la gente fuera sin aviso.']),
  ('FW-014', 'fortigate', array['Entra a System > SNMP y elimina la comunidad public o private.','Crea un usuario SNMP v3 con autenticación SHA y cifrado AES.','Restringe Hosts a la IP del sistema de monitoreo.','Actualiza el monitoreo con las credenciales nuevas antes de borrar las viejas.']),
  ('FW-015', 'fortigate', array['Entra a System > Settings > System Time y selecciona Synchronize with NTP Server.','Usa al menos dos servidores; si tienes controlador de dominio, apunta al mismo que usan los servidores.','Fija la zona horaria correcta: un log con hora equivocada no sirve como evidencia.','Confirma por CLI: diagnose sys ntp status.']),
  ('FW-016', 'fortigate', array['Revisa Dashboard > Licenses y anota qué servicio está vencido o por vencer.','Renueva con el canal antes de la fecha: al vencer, IPS y antivirus dejan de actualizar firmas.','Aplica la licencia en System > FortiGuard y fuerza Update Now.','Verifica que la fecha de las firmas avance después de la renovación.']),
  ('FW-017', 'fortigate', array['Entra a Log & Report > Log Settings y agrega un segundo destino syslog.','Apunta ese destino a un almacenamiento fuera del firewall y fuera del colector.','Envía en formato CEF o syslog estándar para que otro sistema pueda leerlo.','Comprueba que llegan eventos a ambos destinos antes de dar por cerrado el hallazgo.']),
  ('FW-018', 'fortigate', array['Revisa System > HA y compara el estado de los dos miembros.','Identifica si la degradación viene del enlace de heartbeat, de firmware distinto o de una sincronización fallida.','Iguala el firmware de ambos equipos: la HA no sincroniza entre versiones distintas.','Fuerza la sincronización por CLI: diagnose sys ha checksum recalculate.']),
  ('FW-019', 'fortigate', array['Revisa en Log & Report si el equipo está descartando eventos por volumen.','Baja el nivel de detalle de las políticas más ruidosas antes de ampliar el colector.','Verifica que el enlace hacia el colector no esté saturado ni bloqueado por otra política.','Si la pérdida persiste, el colector necesita más disco o más CPU: revisa su dimensionamiento.']),
  ('FW-020', 'fortigate', array['Abre Policy & Objects > Addresses y crea grupos geográficos con los países que no usa tu operación.','Agrega una política de denegación por encima de las de salida con esos grupos como destino.','Activa el registro en esa política: lo bloqueado es la evidencia de que sirve.','Revisa una semana después si alguien legítimo quedó bloqueado, antes de ampliar la lista.']),
  ('OP-001', 'fortigate', array['Programa la revisión de reglas como tarea recurrente cada seis meses.','Genera el informe de hardening de EventReport como punto de partida de la revisión.','Documenta qué se revisó, qué se cambió y quién lo aprobó: eso es lo que pide el control.','Cierra la revisión con el respaldo de configuración del día.']),
  ('OP-002', 'fortigate', array['Abre la lista de eventos críticos en el portal y revisa los que llevan más de siete días.','Asigna un responsable a cada uno; sin responsable el evento no se cierra.','Marca el evento como atendido dejando escrito qué se hizo, aunque la conclusión sea que era legítimo.','Si el evento se repite, conviértelo en una regla o en una alerta, no en una revisión manual más.']),
  ('OP-003', 'fortigate', array['Compara la retención actual con la que exige tu marco: PCI DSS pide un año, con tres meses en línea.','Sube los días de bóveda del colector en Ajustes si el disco lo permite.','Si no alcanza, agrega almacenamiento al colector antes que reducir el detalle de los registros.','Deja escrito el cálculo de retención: el auditor pregunta por qué ese número.']),
  ('OP-004', 'fortigate', array['Entra a Log & Report > Log Settings y confirma que el registro de eventos de administración esté activo.','Prohíbe las cuentas compartidas: si todos entran como admin, ningún cambio tiene autor.','Crea una cuenta nominal por persona y desactiva la genérica.','Verifica en el log que los cambios nuevos traen usuario e IP de origen.']),
  ('FW-001', 'sophos_xg', array['Entra a Administration > Device access y revisa la columna WAN.','Desmarca HTTPS, SSH y Ping para la zona WAN.','Si necesitas administración remota, deja HTTPS y agrega las IP en Local service ACL exception rule.','Prueba desde fuera que el puerto ya no responde antes de cerrar el hallazgo.']),
  ('FW-002', 'sophos_xg', array['Entra a Authentication > One-time password y activa el servicio.','Marca a los administradores en Administration > Device access para exigir OTP.','Entrega el código QR a cada persona y verifica un inicio de sesión antes de forzarlo a todos.','Deja una cuenta de emergencia documentada y guardada fuera del equipo.']),
  ('FW-003', 'sophos_xg', array['Entra a Administration > Device access > Local service ACL exception rule.','Crea la excepción con las redes desde donde se administra y quita el acceso general.','Ordena las reglas: la de denegación amplia debe quedar debajo de la excepción.','Prueba desde una IP no autorizada: debe rechazar la conexión.']),
  ('FW-004', 'sophos_xg', array['Revisa Administration > Device access > Profiles y quién tiene perfil Administrator.','Crea perfiles acotados con solo los módulos que cada rol necesita.','Reasigna las cuentas sobrantes al perfil acotado en Authentication > Users.','Documenta quién aprobó cada perfil total.']),
  ('FW-005', 'sophos_xg', array['Revisa la versión en Control center y compárala con el ciclo de vida publicado por Sophos.','Descarga la versión recomendada desde el portal de Sophos para tu modelo.','Respalda la configuración en Backup & firmware > Backup & restore antes de actualizar.','Actualiza en ventana de mantenimiento y confirma que las suscripciones sigan activas después.']),
  ('FW-006', 'sophos_xg', array['Abre Rules and policies > Firewall rules y localiza la regla señalada.','Reemplaza las zonas y redes Any por los objetos reales de origen y destino.','Cambia el servicio Any por los puertos que la aplicación usa.','Desactiva la regla un día y revisa los contadores antes de eliminarla.']),
  ('FW-007', 'sophos_xg', array['En Rules and policies > Firewall rules activa la columna de uso y ordena por última coincidencia.','Desactiva las reglas sin tráfico en 90 días y anota la fecha.','Espera dos semanas por si existe un proceso mensual.','Elimina las que sigan sin uso, con respaldo previo.']),
  ('FW-008', 'sophos_xg', array['Abre Rules and policies > Firewall rules y filtra las reglas con acción Accept.','Activa Log firewall traffic en cada una.','Confirma en Reports que el tráfico permitido aparece después del cambio.','Verifica que los eventos también lleguen al colector.']),
  ('FW-010', 'sophos_xg', array['Revisa Rules and policies > NAT rules y las reglas DNAT publicadas.','Elimina las que publiquen RDP, SSH, SMB o puertos de base de datos hacia internet.','Sustituye el acceso por VPN con segundo factor.','Para lo que siga publicado, limita el origen a direcciones conocidas.']),
  ('FW-011', 'sophos_xg', array['Entra a Authentication > One-time password y activa OTP para el grupo de VPN.','En VPN > SSL VPN remote access asigna solo grupos con OTP exigido.','Entrega los códigos y prueba con una cuenta antes de aplicarlo a todos.','Revisa el log de autenticación tras el cambio.']),
  ('FW-012', 'sophos_xg', array['Abre VPN > IPsec policies y edita la política del túnel señalado.','Quita DES, 3DES, MD5 y SHA1; deja AES-256 con SHA-256 y DH group 14 o superior.','Coordina con el extremo remoto: el túnel cae hasta que ambos coincidan.','Para SSL VPN, deshabilita TLS 1.0 y 1.1 en la configuración del servicio.']),
  ('FW-013', 'sophos_xg', array['Revisa Certificates > Certificates y localiza el del portal señalado.','Emite o renueva con una autoridad pública para el nombre que usan los usuarios.','Asígnalo en Administration > Admin and user settings o en el servicio correspondiente.','Programa el aviso de renovación con un mes de anticipación.']),
  ('FW-015', 'sophos_xg', array['Entra a Administration > Time y selecciona sincronización con servidor NTP.','Configura al menos dos servidores y la zona horaria correcta.','Si tienes dominio, usa el mismo servidor que los servidores internos.','Confirma que la hora del log coincide con la real después del cambio.']),
  ('FW-016', 'sophos_xg', array['Revisa Administration > Licensing y anota qué módulo está vencido o por vencer.','Renueva con el canal antes de la fecha: sin suscripción, IPS y antivirus dejan de actualizar.','Sincroniza la licencia desde el portal de Sophos.','Verifica que la fecha de las firmas avance tras la renovación.']),
  ('FW-017', 'sophos_xg', array['Entra a Configure > System services > Log settings y agrega un servidor syslog.','Apunta el segundo destino fuera del firewall y fuera del colector.','Selecciona los módulos que deben enviarse, no solo el firewall.','Comprueba que llegan eventos a ambos destinos.']),
  ('FW-018', 'sophos_xg', array['Revisa System services > High availability y el estado de los dos miembros.','Confirma que el enlace dedicado de HA está activo y que el firmware coincide.','Iguala versiones si difieren: la HA no sincroniza entre versiones distintas.','Fuerza la sincronización y revisa el log del par.']),
  ('FW-019', 'sophos_xg', array['Revisa si el equipo descarta eventos por volumen en Log settings.','Reduce el detalle de las reglas más ruidosas antes de ampliar el colector.','Verifica que el camino hacia el colector no esté saturado ni bloqueado.','Si persiste, el colector necesita más disco o CPU.']),
  ('FW-020', 'sophos_xg', array['Crea grupos de país en Hosts and services > Country group con los que no usa tu operación.','Agrega una regla de denegación por encima de las de salida usando esos grupos.','Activa el registro en esa regla.','Revisa una semana después si alguien legítimo quedó bloqueado.']),
  ('OP-001', 'sophos_xg', array['Programa la revisión de reglas cada seis meses como tarea recurrente.','Usa el informe de hardening de EventReport como punto de partida.','Documenta qué se revisó, qué cambió y quién aprobó.','Cierra con el respaldo de configuración del día.']),
  ('OP-002', 'sophos_xg', array['Revisa en el portal los eventos críticos con más de siete días.','Asigna responsable a cada uno.','Márcalo como atendido dejando escrito qué se hizo.','Si se repite, conviértelo en regla o alerta.']),
  ('OP-003', 'sophos_xg', array['Compara la retención actual con la que exige tu marco.','Sube los días de bóveda del colector si el disco lo permite.','Agrega almacenamiento antes que reducir el detalle de los registros.','Deja escrito el cálculo de retención.']),
  ('OP-004', 'sophos_xg', array['Confirma en Log settings que el registro de eventos de administración esté activo.','Elimina las cuentas compartidas: sin cuenta nominal, ningún cambio tiene autor.','Crea una cuenta por persona y desactiva la genérica.','Verifica que los cambios nuevos traigan usuario e IP.'])
on conflict (rule_code, brand) do update set steps = excluded.steps;

commit;
